export const ERROR_TYPE_VALIDATION_ERROR = 'COUPONJS_VALIDATION_ERROR';
export const ERROR_TYPE_CHARACTER_SET_ERROR = 'COUPONJS_CHARACTER_SET_ERROR';
export const ERROR_TYPE_FORMAT_ERROR = 'COUPONJS_FORMAT_ERROR';
export const ERROR_TYPE_GENERATE_COUPON_CONFIGURATION_ERROR = 'COUPONJS_GENERATE_COUPON_CONFIGURATION_ERROR';
export const ERROR_TYPE_COUPON_ENGINE_CONFIGURATION_ERROR = 'COUPONJS_COUPON_ENGINE_CONFIGURATION_ERROR';
export const ERROR_CONSTANTS = {
  [ERROR_TYPE_VALIDATION_ERROR]: {
    type: ERROR_TYPE_VALIDATION_ERROR,
    message: 'Validation error'
  },
  [ERROR_TYPE_CHARACTER_SET_ERROR]: {
    type: ERROR_TYPE_CHARACTER_SET_ERROR,
    message: 'Character set error'
  },
  [ERROR_TYPE_FORMAT_ERROR]: {
    type: ERROR_TYPE_FORMAT_ERROR,
    message: 'Format error'
  },
  [ERROR_TYPE_GENERATE_COUPON_CONFIGURATION_ERROR]: {
    type: ERROR_TYPE_GENERATE_COUPON_CONFIGURATION_ERROR,
    message: 'Generate coupon configuration error'
  },
  [ERROR_TYPE_COUPON_ENGINE_CONFIGURATION_ERROR]: {
    type: ERROR_TYPE_COUPON_ENGINE_CONFIGURATION_ERROR,
    message: 'Coupon engine configuration error'
  }
};
