export const COUPONJS = 'COUPONJS';
export const MIN_NUMBER_OF_COUPONS_TO_GENERATE = 1;
export const MAX_NUMBER_OF_COUPONS_TO_GENERATE = 100000;
export const DEFAULT_NUMBER_OF_COUPONS_TO_GENERATE = MIN_NUMBER_OF_COUPONS_TO_GENERATE;
export const MAX_LENGTH = 128;
export const MIN_LENGTH = 1;
export const DEFAULT_LENGTH = 6;
export const DEFAULT_PREFIX = '';
export const DEFAULT_SUFFIX = '';
export const ALPHABET_UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
export const ALPHABET_LOWERCASE = 'abcdefghijklmnopqrstuvwxyz';
export const DIGIT = '0123456789';
export const BINARY = '01';
export const OCTAL = '01234567';
export const HEX = '0123456789ABCDEF';
export const HEX_LOWER = '0123456789abcdef';
export const ALNUM = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
export const CHARSET_ALPHA = 'CHARSET_ALPHA';
export const CHARSET_ALPHA_LOWER = 'CHARSET_ALPHA_LOWER';
export const CHARSET_DIGIT = 'CHARSET_DIGIT';
export const CHARSET_ALNUM = 'CHARSET_ALNUM';
export const CHARSET_BINARY = 'CHARSET_BINARY';
export const CHARSET_OCTAL = 'CHARSET_OCTAL';
export const CHARSET_HEX = 'CHARSET_HEX';
export const CHARSET_HEX_LOWER = 'CHARSET_HEX_LOWER';
export const DEFAULT_OMIT_CHARACTERS = [];
export const UNDEFINED = 'UNDEFINED';
export const DEFAULT_COUPON_FORMAT = UNDEFINED;
export const DEFAULT_CUSTOM_CHARACTER_SET = [];
export const DEFAULT_BUILTIN_CHARACTER_SET = [CHARSET_ALPHA];
export const DEFAULT_CHARACTER_SET_OPTION = {
  builtIn: DEFAULT_BUILTIN_CHARACTER_SET,
  custom: DEFAULT_CUSTOM_CHARACTER_SET
};
