const MIN_NUMBER_OF_COUPONS_TO_GENERATE = 1;
const MAX_NUMBER_OF_COUPONS_TO_GENERATE = 100000;
const DEFAULT_NUMBER_OF_COUPONS_TO_GENERATE = MIN_NUMBER_OF_COUPONS_TO_GENERATE;
const MAX_LENGTH = 128;
const MIN_LENGTH = 1;
const DEFAULT_LENGTH = 6;
const DEFAULT_PREFIX = '';
const DEFAULT_SUFFIX = '';
const ALPHABET_UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const ALPHABET_LOWERCASE = 'abcdefghijklmnopqrstuvwxyz';
const DIGIT = '0123456789';
const BINARY = '01';
const OCTAL = '01234567';
const HEX = `${DIGIT}ABCDEF`;
const HEX_LOWER = `${DIGIT}abcdef`;
const CHARSET_ALPHA = 'CHARSET_ALPHA';
const CHARSET_ALPHA_LOWER = 'CHARSET_ALPHA_LOWER';
const CHARSET_DIGIT = 'CHARSET_DIGIT';
const CHARSET_ALNUM = 'CHARSET_ALNUM';
const CHARSET_BINARY = 'CHARSET_BINARY';
const CHARSET_OCTAL = 'CHARSET_OCTAL';
const CHARSET_HEX = 'CHARSET_HEX';
const CHARSET_HEX_LOWER = 'CHARSET_HEX_LOWER';

/**
 * @type {{MIN_NUMBER_OF_COUPONS_TO_GENERATE: number, MAX_NUMBER_OF_COUPONS_TO_GENERATE: number, DEFAULT_NUMBER_OF_COUPONS_TO_GENERATE: number, MAX_LENGTH: number, MIN_LENGTH: number, DEFAULT_LENGTH: number, DEFAULT_PREFIX: string, DEFAULT_SUFFIX: string, ALPHABET_UPPERCASE: string, ALPHABET_LOWERCASE: string, DIGIT: string, BINARY: string, OCTAL: string, HEX: string, HEX_LOWER: string, CHARSET_ALPHA: string, CHARSET_ALPHA_LOWER: string, CHARSET_DIGIT: string, CHARSET_ALNUM: string, CHARSET_BINARY: string, CHARSET_OCTAL: string, CHARSET_HEX: string, CHARSET_HEX_LOWER: string}}
 */
module.exports = {
  MIN_NUMBER_OF_COUPONS_TO_GENERATE,
  MAX_NUMBER_OF_COUPONS_TO_GENERATE,
  DEFAULT_NUMBER_OF_COUPONS_TO_GENERATE,
  MAX_LENGTH,
  MIN_LENGTH,
  DEFAULT_LENGTH,
  DEFAULT_PREFIX,
  DEFAULT_SUFFIX,
  ALPHABET_UPPERCASE,
  ALPHABET_LOWERCASE,
  DIGIT,
  BINARY,
  OCTAL,
  HEX,
  HEX_LOWER,
  CHARSET_ALPHA,
  CHARSET_ALPHA_LOWER,
  CHARSET_DIGIT,
  CHARSET_ALNUM,
  CHARSET_BINARY,
  CHARSET_OCTAL,
  CHARSET_HEX,
  CHARSET_HEX_LOWER
};
