/**
 * @type {{MAX_LENGTH: number, MIN_LENGTH: number, DEFAULT_LENGTH: number, DEFAULT_PREFIX: string, DEFAULT_SUFFIX: string, ALPHABET_UPPERCASE: string, ALPHABET_LOWERCASE: string, DIGIT: string, CHARSET_ALPHA: string, CHARSET_ALPHA_LOWER: string, CHARSET_DIGIT: string, CHARSET_ALNUM: string}}
 */
module.exports = {
  MAX_LENGTH: 128,
  MIN_LENGTH: 1,
  DEFAULT_LENGTH: 6,
  DEFAULT_PREFIX: '',
  DEFAULT_SUFFIX: '',
  ALPHABET_UPPERCASE: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  ALPHABET_LOWERCASE: 'abcdefghijklmnopqrstuvwxyz',
  DIGIT: '0123456789',
  CHARSET_ALPHA: 'CHARSET_ALPHA',
  CHARSET_ALPHA_LOWER: 'CHARSET_ALPHA_LOWER',
  CHARSET_DIGIT: 'CHARSET_DIGIT',
  CHARSET_ALNUM: 'CHARSET_ALNUM'
};